### ISSUE TITLE
Default Currency not working?

### ISSUE THREAD

**Issue by masterakado** [Torann/laravel-currency#22] opened 2014-10-09 17:54 UTC
Hello, I used this package to display currencies for an ecomm site but the default settings I use are not working. 
I made EUR the default currency in the config.php, but my currency always displays as USD. I have to use  EUR as the second parameter in the function to display my currency as EUR.
I've also tried the currency:cleanup and currency:update commands with no success. 
Don't know if it's a real problem, but I thought I should submit it.
Thanks.

**Comment by Torann** [comment] 2016-03-22 20:22
Not sure what was going on here. I can't reproduce this.

**Comment by FiloSpaTeam** [comment] 2016-03-24 10:07
The problem is that:
i'm italian and our currency is EUR.
But if you set EUR in default config you don't really work with EUR, but with USD converted in EUR.

Example:
I saved in database 1000.00 (numeric value).
If i use EUR as default, those are 1000.00 Euro,
if i use USD as default, those are 1000.00 USD,

now, if i set EUR as default but get them as USD, we have 1000 * 0,89 = 890 Euro
1000 is not 890.

**Comment by Torann** [comment] 2016-09-29 20:47
This is fixed in the upcoming version 1.0 release

**Closed by Torann** 2016-09-29 20:47 UTC
